steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'Dockerfile.train'
      - '-t'
      - '${_IMAGE_URI}'
      - '.'
  
  # Push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_IMAGE_URI}'

images:
  - '${_IMAGE_URI}'

options:
  machineType: 'E2_HIGHCPU_8'
